name: lint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Install clang-format
        shell: bash
        run: sudo apt install clang-format-13

      - name: 🖨️ Cloning .clang-format from repo
        if: ${{ inputs.library != '' }}
        run: wget https://raw.githubusercontent.com/imdominicreed/just-a-random-webserver/lint/.clang-format -O .clang-format

      - name: Lint
        shell: bash
        if: always()
        run: |
             clang-format --dry-run --Werror \
             $(find include -name "*.h")
             $(find src -name "*.cc")
